/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

import com.carbonell.melodyseer.models.MyFile;
import java.awt.Color;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.SwingWorker;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author marta
 */
public class DownloadPanel extends javax.swing.JPanel {

    Main jFrameMain;
    private String lastSavedFile;
    File currentFile;
    private MediaPanel mediaPanel;
    private final Color DARK_GREEN =  new Color(0, 153, 51);
    private final Color DARK_RED = new Color (153,0, 51);

    /**
     * Creates new form DownloadPanel
     *
     * @param jFrameMain
     */
    public DownloadPanel(Main jFrameMain) {
        initComponents();
        setSize(800, 800);
        pnlDownloads.setSize(800, 270);
        pnlMedia.setSize(800, 480);
        
        this.jFrameMain = jFrameMain;
        cmbAudioFormat.setVisible(false);
        txtSaveTo.setText(jFrameMain.getSaveToPath());
        
        MigLayout layout = new MigLayout(
                "wrap 3, fillx, align center top",
                "[right][left][left]",
                "[]12[]12[]12[]12[]12[]12[]"
        );
        pnlDownloads.setLayout(layout);
        
        pnlDownloads.add(lblUrl);
        pnlDownloads.add(txtUrl, "growx");
        pnlDownloads.add(chkOpen);
        
        pnlDownloads.add(lblChoose);
        pnlDownloads.add(radVideo, "split 3");
        pnlDownloads.add(cmbVideoFormat, "wrap, left");
        
        pnlDownloads.add(radMp3, "skip 1, split 3");
        pnlDownloads.add(cmbAudioFormat, "wrap, left");
        
        pnlDownloads.add(lblSaveTo);
        pnlDownloads.add(txtSaveTo, "growx");
        pnlDownloads.add(btnSaveTo);
        
        pnlDownloads.add(btnDownload, "skip 1, wrap, center");
        
        pnlDownloads.add(lblProgress);
        pnlDownloads.add(prgDownload, "growx, wrap");
        
        pnlDownloads.add(lblError, "skip 1, center, wrap");

        mediaPanel = new MediaPanel(jFrameMain);
        mediaPanel.setLocation(0, 10);
        pnlMedia.add(mediaPanel);
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpFormat = new javax.swing.ButtonGroup();
        pnlDownloads = new javax.swing.JPanel();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        chkOpen = new javax.swing.JCheckBox();
        lblChoose = new javax.swing.JLabel();
        radVideo = new javax.swing.JRadioButton();
        cmbVideoFormat = new javax.swing.JComboBox<>();
        radMp3 = new javax.swing.JRadioButton();
        cmbAudioFormat = new javax.swing.JComboBox<>();
        lblSaveTo = new javax.swing.JLabel();
        txtSaveTo = new javax.swing.JTextField();
        btnSaveTo = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        lblProgress = new javax.swing.JLabel();
        prgDownload = new javax.swing.JProgressBar();
        lblError = new javax.swing.JLabel();
        pnlMedia = new javax.swing.JPanel();

        setLayout(null);

        pnlDownloads.setLayout(null);

        lblUrl.setText("Insert video URL here:");
        pnlDownloads.add(lblUrl);
        lblUrl.setBounds(40, 60, 150, 16);
        pnlDownloads.add(txtUrl);
        txtUrl.setBounds(200, 50, 410, 30);

        chkOpen.setSelected(true);
        chkOpen.setText("Open after download");
        chkOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpenActionPerformed(evt);
            }
        });
        pnlDownloads.add(chkOpen);
        chkOpen.setBounds(620, 50, 150, 20);

        lblChoose.setText("Choose format...");
        pnlDownloads.add(lblChoose);
        lblChoose.setBounds(40, 110, 130, 16);

        grpFormat.add(radVideo);
        radVideo.setSelected(true);
        radVideo.setText("Video");
        radVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radVideoActionPerformed(evt);
            }
        });
        pnlDownloads.add(radVideo);
        radVideo.setBounds(180, 110, 53, 21);

        cmbVideoFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MP4", "MKV" }));
        cmbVideoFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVideoFormatActionPerformed(evt);
            }
        });
        pnlDownloads.add(cmbVideoFormat);
        cmbVideoFormat.setBounds(290, 110, 72, 22);

        grpFormat.add(radMp3);
        radMp3.setText("Audio");
        radMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMp3ActionPerformed(evt);
            }
        });
        pnlDownloads.add(radMp3);
        radMp3.setBounds(180, 150, 55, 21);

        cmbAudioFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MP3", "WAV" }));
        cmbAudioFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAudioFormatActionPerformed(evt);
            }
        });
        pnlDownloads.add(cmbAudioFormat);
        cmbAudioFormat.setBounds(290, 150, 72, 22);

        lblSaveTo.setText("Save to...");
        pnlDownloads.add(lblSaveTo);
        lblSaveTo.setBounds(40, 200, 90, 20);

        txtSaveTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaveToActionPerformed(evt);
            }
        });
        pnlDownloads.add(txtSaveTo);
        txtSaveTo.setBounds(200, 200, 410, 30);

        btnSaveTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        btnSaveTo.setText("Choose");
        btnSaveTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToActionPerformed(evt);
            }
        });
        pnlDownloads.add(btnSaveTo);
        btnSaveTo.setBounds(630, 210, 100, 23);

        btnDownload.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/downloadyt.png"))); // NOI18N
        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        pnlDownloads.add(btnDownload);
        btnDownload.setBounds(310, 240, 210, 40);

        lblProgress.setText("Progress");
        pnlDownloads.add(lblProgress);
        lblProgress.setBounds(30, 300, 60, 20);
        pnlDownloads.add(prgDownload);
        prgDownload.setBounds(120, 300, 630, 20);

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlDownloads.add(lblError);
        lblError.setBounds(120, 330, 630, 0);

        add(pnlDownloads);
        pnlDownloads.setBounds(0, 10, 820, 400);

        pnlMedia.setLayout(null);
        add(pnlMedia);
        pnlMedia.setBounds(10, 280, 760, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void chkOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOpenActionPerformed

    private void btnSaveToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToActionPerformed

        // https://www.youtube.com/watch?v=HQ8JAbHmOvs
        // https://stackoverflow.com/questions/10083447/selecting-folder-destination-in-java
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String saveToPath = f.getAbsolutePath();
            jFrameMain.setSaveToPath(saveToPath);
            txtSaveTo.setText(jFrameMain.getSaveToPath());
            System.out.println(saveToPath);
        }
    }//GEN-LAST:event_btnSaveToActionPerformed

    private void radVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radVideoActionPerformed
        cmbAudioFormat.setVisible(false);
        cmbVideoFormat.setVisible(true);
        jFrameMain.setFormat(cmbVideoFormat.getSelectedItem().toString().toLowerCase());
    }//GEN-LAST:event_radVideoActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        if (radMp3.isSelected()) {
            downloadAudio();
        } else if (radVideo.isSelected()) {
            downloadVideo();
        } else {
            downloadVideo();
        }

    }//GEN-LAST:event_btnDownloadActionPerformed

    private void cmbVideoFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVideoFormatActionPerformed
        jFrameMain.setFormat(cmbVideoFormat.getSelectedItem().toString().toLowerCase());
    }//GEN-LAST:event_cmbVideoFormatActionPerformed

    private void cmbAudioFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAudioFormatActionPerformed
        jFrameMain.setFormat(cmbAudioFormat.getSelectedItem().toString().toLowerCase());
    }//GEN-LAST:event_cmbAudioFormatActionPerformed

    private void radMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMp3ActionPerformed
        cmbAudioFormat.setVisible(true);
        cmbVideoFormat.setVisible(false);
        jFrameMain.setFormat(cmbAudioFormat.getSelectedItem().toString().toLowerCase());
    }//GEN-LAST:event_radMp3ActionPerformed

    private void txtSaveToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaveToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaveToActionPerformed

    private void downloadVideo() {

        if (!checkYtdlp()) {
            setMessage("Cannot find yt-dlp. Go to preferences and set path manually.", DARK_RED);
            return;
        }

        // Código proporcionado por el profesor
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    String downloadSpeedCommand = getDownloadSpeedCommand();
                    ProcessBuilder pb;
                    if (downloadSpeedCommand.equals("")) {
                        pb = new ProcessBuilder(jFrameMain.getYtdlp_path(),
                                txtUrl.getText(),
                                "-t",
                                jFrameMain.getFormat(),
                                "-P",
                                "\"" + jFrameMain.getSaveToPath() + "\"",
                                "-P",
                                "temp:"
                                + jFrameMain.getSaveToPathTemp());
                    } else {
                        pb = new ProcessBuilder(jFrameMain.getYtdlp_path(),
                                txtUrl.getText(),
                                "-t",
                                "\"" + jFrameMain.getFormat() + "\"",
                                "-P",
                                jFrameMain.getSaveToPath(),
                                "-P",
                                "temp:"
                                + jFrameMain.getSaveToPathTemp(),
                                downloadSpeedCommand);
                    }
                    pb.redirectErrorStream(true); // Combine stdout and stderr
                    Process process = pb.start();

                    // Read output
                    BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                    String line;
                    StringBuilder output = new StringBuilder();
                    while ((line = reader.readLine()) != null) {
                        output.append(line).append("\n");
                        publish(line); // https://stackoverflow.com/questions/18535303/how-are-the-publish-and-process-methods-on-swingworker-properly-used                        
                    }

                    int exitCode = process.waitFor();

                    publish("Exited with code: " + exitCode + "\n");

                } catch (IOException | InterruptedException e) {
                    publish("Error: " + e.getMessage());
                }
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                processDownload(chunks, jFrameMain.getFormat());

            }

            @Override
            protected void done() {
                try {
                    setMessage("File has been downloaded succesfully!", DARK_GREEN);
                    if (chkOpen.isSelected() && lastSavedFile != null) {
                        openMedia();
                    }
                } catch (IOException e) {

                }
            }

        };

        worker.execute();

    }

    private void processDownload(List<String> chunks, String extension) {
        System.out.println("Process> " + chunks.size() + " lines recieved. In thread " + Thread.currentThread());
        for (String line : chunks) {
            Pattern pattern = Pattern.compile("\\d+\\.?\\d*\\%");
            Matcher matcher = pattern.matcher(line);

            System.out.println("\t" + line);

            if (line.toLowerCase().contains("forbidden")) {
                setMessage("There is a problem with YouTube right now. Please, try later.", DARK_RED);
            }

            if (line.contains("Moving file") && line.toLowerCase().contains("." + extension.toLowerCase())) {
                lastSavedFile = line.split("\" to \"")[1];
                lastSavedFile = lastSavedFile.substring(0, lastSavedFile.length() - 1);
                currentFile = new File(lastSavedFile);
                MyFile newFile = new MyFile(currentFile, txtUrl.getText());
                jFrameMain.addNewFile(newFile);
            } else if (line.contains("Merging") && line.toLowerCase().contains("." + extension.toLowerCase())) {
                String stringToRemove = "[Merger] Merging formats into";
                lastSavedFile = line.substring(line.indexOf(stringToRemove) + stringToRemove.length()).trim();
                currentFile = new File(lastSavedFile.replace("\"", ""));
                MyFile newFile = new MyFile(currentFile, txtUrl.getText());
                jFrameMain.addNewFile(newFile);
            }

            if (matcher.find()) {
                // https://stackoverflow.com/questions/25277300/how-to-return-a-string-which-matches-the-regex-in-java
                // https://docs.oracle.com/javase/tutorial/uiswing/components/progress.html
                double progress = Double.parseDouble(matcher.group().replace("%", ""));
                prgDownload.setValue((int) progress);
            }

        }
    }

    private void openMedia() throws IOException {
        if (chkOpen.isSelected()) {
            try {
                // https://stackoverflow.com/questions/26334556/open-a-file-using-desktopjava-awt
                Desktop desktop = Desktop.getDesktop();
                desktop.open(currentFile);
//            ProcessBuilder pb = new ProcessBuilder(lastSavedFile);
//            pb.redirectErrorStream(true); 
//            Process process = pb.start(); 
            } catch (Exception e) {

            }
        }
    }

    private String getDownloadSpeedCommand() {
        if (!jFrameMain.getSelectedSpeed().equals("") && !jFrameMain.getSelectedSpeed().equals("Don't limit")) {
            return "-r" + jFrameMain.getSelectedSpeed().split(" ")[0] + "M";
        } else {
            return "";
        }
    }

    private void downloadAudio() {
        if (!checkYtdlp()) {
            setMessage("Cannot find yt-dlp. Go to preferences and set path manually.", DARK_RED);
            return;
        }

        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    String downloadSpeedCommand = getDownloadSpeedCommand();
                    ProcessBuilder pb;
                    if (downloadSpeedCommand.equals("")) {
                        pb = new ProcessBuilder(jFrameMain.getYtdlp_path(),
                                "-x",
                                "--audio-format=\"" + jFrameMain.getFormat() + "\"",
                                "-P",
                                jFrameMain.getSaveToPath(),
                                "-P",
                                "temp:"
                                + jFrameMain.getSaveToPathTemp(),
                                txtUrl.getText());
                    } else {
                        pb = new ProcessBuilder(jFrameMain.getYtdlp_path(),
                                "-x",
                                "--audio-format=\"" + jFrameMain.getFormat() + "\"",
                                "-P",
                                jFrameMain.getSaveToPath(),
                                "-P",
                                "temp:"
                                + jFrameMain.getSaveToPathTemp(),
                                txtUrl.getText(),
                                downloadSpeedCommand);
                    }
                    pb.redirectErrorStream(true); // Combine stdout and stderr
                    Process process = pb.start();

                    // Read output
                    BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                    String line;
                    StringBuilder output = new StringBuilder();
                    while ((line = reader.readLine()) != null) {
                        output.append(line).append("\n");
                        publish(line); // https://stackoverflow.com/questions/18535303/how-are-the-publish-and-process-methods-on-swingworker-properly-used                        
                    }

                    int exitCode = process.waitFor();

                    publish("Exited with code: " + exitCode + "\n");

                } catch (IOException | InterruptedException e) {
                    publish("Error: " + e.getMessage());
                }
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                processDownload(chunks, jFrameMain.getFormat());
            }

            @Override
            protected void done() {
                try {
                    setMessage("File has been downloaded succesfully!", DARK_GREEN);
                    if (chkOpen.isSelected() && lastSavedFile != null) {
                        openMedia();
                    }
                } catch (IOException e) {

                }
            }
        };
        worker.execute();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSaveTo;
    private javax.swing.JCheckBox chkOpen;
    private javax.swing.JComboBox<String> cmbAudioFormat;
    private javax.swing.JComboBox<String> cmbVideoFormat;
    private javax.swing.ButtonGroup grpFormat;
    private javax.swing.JLabel lblChoose;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblSaveTo;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JPanel pnlDownloads;
    private javax.swing.JPanel pnlMedia;
    private javax.swing.JProgressBar prgDownload;
    private javax.swing.JRadioButton radMp3;
    private javax.swing.JRadioButton radVideo;
    private javax.swing.JTextField txtSaveTo;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables

    void refreshFiles() {
        mediaPanel.refreshModel();
    }

    private boolean checkYtdlp() {
        return new File(jFrameMain.getYtdlp_path()).exists();
    }

    private void setMessage(String message, Color c) {
       lblError.setText(message);
       lblError.setForeground(c);
       lblError.setVisible(!message.isEmpty());
    }
}
