/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

/**
 *
 * @author marta
 */
public class DownloadPanel extends javax.swing.JPanel {

    /**
     * Creates new form DownloadPanel
     */
    public DownloadPanel() {
        initComponents();
        setSize(800, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpFormat = new javax.swing.ButtonGroup();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        chkOpen = new javax.swing.JCheckBox();
        btnDownload = new javax.swing.JButton();
        lblProgress = new javax.swing.JLabel();
        prgProgress = new javax.swing.JProgressBar();
        scrOutput = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();
        btnHide = new javax.swing.JButton();
        lblChoose = new javax.swing.JLabel();
        lblSaveTo = new javax.swing.JLabel();
        btnSaveTo = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        cmbVideoFormat = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(null);

        lblUrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yt.png"))); // NOI18N
        lblUrl.setText("Insert video URL here:");
        add(lblUrl);
        lblUrl.setBounds(40, 60, 140, 16);
        add(txtUrl);
        txtUrl.setBounds(190, 50, 410, 30);

        chkOpen.setSelected(true);
        chkOpen.setText("Open after download");
        chkOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpenActionPerformed(evt);
            }
        });
        add(chkOpen);
        chkOpen.setBounds(620, 50, 150, 20);

        btnDownload.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/downloadyt.png"))); // NOI18N
        btnDownload.setText("Download");
        add(btnDownload);
        btnDownload.setBounds(280, 330, 230, 90);

        lblProgress.setText("Progress");
        add(lblProgress);
        lblProgress.setBounds(40, 450, 60, 20);
        add(prgProgress);
        prgProgress.setBounds(130, 450, 630, 20);

        txaOutput.setEditable(false);
        txaOutput.setColumns(20);
        txaOutput.setRows(5);
        scrOutput.setViewportView(txaOutput);

        add(scrOutput);
        scrOutput.setBounds(30, 500, 740, 180);

        btnHide.setText("Hide");
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });
        add(btnHide);
        btnHide.setBounds(330, 720, 72, 23);

        lblChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/choose.png"))); // NOI18N
        lblChoose.setText("Choose format...");
        add(lblChoose);
        lblChoose.setBounds(40, 110, 130, 16);

        lblSaveTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        lblSaveTo.setText("Save to...");
        add(lblSaveTo);
        lblSaveTo.setBounds(40, 230, 90, 20);

        btnSaveTo.setText("Choose");
        btnSaveTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToActionPerformed(evt);
            }
        });
        add(btnSaveTo);
        btnSaveTo.setBounds(150, 230, 75, 23);

        grpFormat.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Video");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1);
        jRadioButton1.setBounds(180, 110, 53, 21);

        grpFormat.add(jRadioButton2);
        jRadioButton2.setText("Audio");
        add(jRadioButton2);
        jRadioButton2.setBounds(180, 180, 55, 21);

        cmbVideoFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MP4", "MOV", "WEBM" }));
        add(cmbVideoFormat);
        cmbVideoFormat.setBounds(290, 110, 72, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MP3", "WAV" }));
        add(jComboBox1);
        jComboBox1.setBounds(290, 180, 72, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void chkOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOpenActionPerformed

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHideActionPerformed

    private void btnSaveToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveToActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnSaveTo;
    private javax.swing.JCheckBox chkOpen;
    private javax.swing.JComboBox<String> cmbVideoFormat;
    private javax.swing.ButtonGroup grpFormat;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblChoose;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblSaveTo;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JProgressBar prgProgress;
    private javax.swing.JScrollPane scrOutput;
    private javax.swing.JTextArea txaOutput;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
