/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

import com.carbonell.melodyseer.models.MyFile;
import com.carbonell.melodyseer.models.MyFileTableModel;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;

/**
 *
 * @author marta
 */
public class MediaPanel extends javax.swing.JPanel {

    Main jFrameMain;

    private javax.swing.JList<MyFile> lstDate;
    private javax.swing.JScrollPane scrDate;
    private javax.swing.JComboBox<MyFile> cmbFormat;

    /**
     * Creates new form MediaPanel
     */
    public MediaPanel(Main jFrameMain) {
        initComponents();
        setSize(800, 800);
        this.jFrameMain = jFrameMain;

        ArrayList placeholder = new ArrayList<>();
        // https://stackoverflow.com/questions/3179136/jtable-how-to-refresh-table-model-after-insert-delete-or-update-the-data
        tblDownloads.setModel(new MyFileTableModel(placeholder));

        lstDate = new javax.swing.JList<>();
        scrDate = new JScrollPane();
        scrDate.setViewportView(lstDate);
        add(scrDate);

        scrDate.setBounds(150, 100, 220, 160);

        cmbFormat = new JComboBox<>();
        cmbFormat.setBounds(470, 100, 150, 22);
        add(cmbFormat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hideMedia = new javax.swing.JButton();
        scrDwnld = new javax.swing.JScrollPane();
        tblDownloads = new javax.swing.JTable();
        lblDownloads = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        hideMedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        hideMedia.setText("Hide Media");
        hideMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideMediaActionPerformed(evt);
            }
        });
        add(hideMedia);
        hideMedia.setBounds(610, 20, 160, 40);

        tblDownloads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrDwnld.setViewportView(tblDownloads);

        add(scrDwnld);
        scrDwnld.setBounds(50, 350, 700, 350);

        lblDownloads.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDownloads.setText("Your downloads");
        add(lblDownloads);
        lblDownloads.setBounds(50, 320, 120, 20);

        lblDate.setText("Download date");
        add(lblDate);
        lblDate.setBounds(50, 100, 110, 16);

        lblFormat.setText("Format");
        add(lblFormat);
        lblFormat.setBounds(420, 100, 70, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Filters");
        add(jLabel1);
        jLabel1.setBounds(50, 50, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void hideMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideMediaActionPerformed
        jFrameMain.showDownloadPanel();
    }//GEN-LAST:event_hideMediaActionPerformed

//    private void onDownloadedFile(MyFile newFile) {
//        ArrayList placeholder = new ArrayList<>();
//        // https://stackoverflow.com/questions/3179136/jtable-how-to-refresh-table-model-after-insert-delete-or-update-the-data
//        tblDownloads.setModel(new MyFileTableModel(placeholder));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hideMedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDownloads;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JScrollPane scrDwnld;
    private javax.swing.JTable tblDownloads;
    // End of variables declaration//GEN-END:variables
}
