/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

import com.carbonell.melodyseer.models.MyFile;
import com.carbonell.melodyseer.models.MyFileDateModel;
import com.carbonell.melodyseer.models.MyFileMimeModel;
import com.carbonell.melodyseer.models.MyFileTableModel;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author marta
 */
public class MediaPanel extends javax.swing.JPanel {

    Main jFrameMain;

    private javax.swing.JList<MyFileDateModel> lstDate;
    private javax.swing.JScrollPane scrDate;
    private javax.swing.JComboBox<MyFileMimeModel> cmbFormat;
    private MyFileTableModel mftm;
    int modelRow;
    private TableRowSorter<MyFileTableModel> sorter;

    /**
     * Creates new form MediaPanel
     */
    public MediaPanel(Main jFrameMain) {
        initComponents();
        setSize(800, 800);
        this.jFrameMain = jFrameMain;

        mftm = new MyFileTableModel(jFrameMain);
        tblDownloads.setModel(mftm);

        sorter = new TableRowSorter<>(mftm);
        tblDownloads.setRowSorter(sorter);

        lstDate = new javax.swing.JList<>();
        scrDate = new JScrollPane();
        scrDate.setViewportView(lstDate);
        add(scrDate);

        scrDate.setBounds(150, 100, 220, 160);

        cmbFormat = new JComboBox<>();
        cmbFormat.setBounds(470, 100, 200, 22);
        add(cmbFormat);

        cmbFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterFormat();
            }
        });

        lstDate.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                filterDate();
            }
        });

        loadFormatFromFile();
        loadDateFromFile();
    }

    private void loadFormatFromFile() {
        var format = jFrameMain.getMyFiles();
        DefaultComboBoxModel<MyFileMimeModel> dcbm = new DefaultComboBoxModel<>();
        for (MyFile f : format) {
            dcbm.addElement(new MyFileMimeModel(f));
        }
        cmbFormat.setModel(dcbm);
    }

    private void loadDateFromFile() {
        var date = jFrameMain.getMyFiles();
        DefaultListModel<MyFileDateModel> dlm = new DefaultListModel<>();
        for (MyFile f : date) {
            dlm.addElement(new MyFileDateModel(f));
        }
        lstDate.setModel(dlm);
    }

    private void filterFormat() {
        String filterText = cmbFormat.getSelectedItem().toString();

        if (filterText == null || filterText.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(Pattern.quote(filterText), 2));
        }
        //System.out.println("DEBUG - Expected result: " + mftm.getValueAt(0, 2));
        //System.out.println("DEBUG -  Filter: " + cmbFormat.getSelectedItem());
    }

    private void filterDate() {
        String filterText = lstDate.getSelectedValue().toString();

        if (filterText == null || filterText.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(Pattern.quote(filterText), 3));
        }
        //System.out.println("DEBUG - Expected result: " + mftm.getValueAt(0, 3));
        //System.out.println("DEBUG -  Filter: " + lstDate.getSelectedValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hideMedia = new javax.swing.JButton();
        scrDwnld = new javax.swing.JScrollPane();
        tblDownloads = new javax.swing.JTable();
        lblDownloads = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();
        lblFiles = new javax.swing.JLabel();
        btnDeleteItem = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();

        setLayout(null);

        hideMedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        hideMedia.setText("Hide Media");
        hideMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideMediaActionPerformed(evt);
            }
        });
        add(hideMedia);
        hideMedia.setBounds(610, 20, 160, 40);

        tblDownloads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrDwnld.setViewportView(tblDownloads);

        add(scrDwnld);
        scrDwnld.setBounds(60, 310, 700, 320);

        lblDownloads.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDownloads.setText("Your downloads");
        add(lblDownloads);
        lblDownloads.setBounds(60, 280, 120, 20);

        lblDate.setText("Download date");
        add(lblDate);
        lblDate.setBounds(50, 100, 110, 16);

        lblFormat.setText("Format");
        add(lblFormat);
        lblFormat.setBounds(420, 100, 70, 16);

        lblFiles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFiles.setText("Files");
        add(lblFiles);
        lblFiles.setBounds(50, 50, 90, 30);

        btnDeleteItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteItem.setText("Delete selected item");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });
        add(btnDeleteItem);
        btnDeleteItem.setBounds(300, 650, 180, 23);
        add(txtFilter);
        txtFilter.setBounds(200, 280, 270, 22);

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        add(btnFilter);
        btnFilter.setBounds(490, 280, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void hideMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideMediaActionPerformed
        jFrameMain.showDownloadPanel();
    }//GEN-LAST:event_hideMediaActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        modelRow = tblDownloads.convertRowIndexToModel(tblDownloads.getSelectedRow());
        ArrayList<MyFile> files = jFrameMain.getMyFiles();
        MyFile currentFile = files.get(modelRow);
        if (!files.isEmpty()) {
            currentFile.delete();
            jFrameMain.deleteFile(modelRow);
            refreshModel();
        }
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        filterFormat();
    }//GEN-LAST:event_btnFilterActionPerformed

    void refreshModel() {
        loadFormatFromFile();
        loadDateFromFile();
        tblDownloads.setModel(new MyFileTableModel(jFrameMain));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton hideMedia;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDownloads;
    private javax.swing.JLabel lblFiles;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JScrollPane scrDwnld;
    private javax.swing.JTable tblDownloads;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

}
