/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

import com.carbonell.melody.seer.component.NewMediaEventObject;
import com.carbonell.melody.seer.component.OnNewMediaAddedListener;
import com.carbonell.melody.seer.component.api.Media;
import com.carbonell.melodyseer.models.MyFile;
import com.carbonell.melodyseer.models.MyFileTableModel;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author marta
 */
public class MediaPanel extends javax.swing.JPanel implements OnNewMediaAddedListener {

    Main jFrameMain;

    private javax.swing.JComboBox<String> cmbFormat;
    int modelRow;
    private TableRowSorter<MyFileTableModel> sorter;
    private ArrayList<MyFile> allFiles = new ArrayList<>();
    private ArrayList<Media> discoveredFiles = new ArrayList<>();

    /**
     * Creates new form MediaPanel
     */
    public MediaPanel(Main jFrameMain) {
        initComponents();
        setSize(760, 340);
        this.jFrameMain = jFrameMain;

        ArrayList<MyFile> localFiles = jFrameMain.getMyFiles();
        for (MyFile localFile : localFiles) {
            allFiles.add(localFile);
        }

        cmbFormat = new JComboBox<>();
        cmbFormat.setBounds(490, 27, 90, 22);
        add(cmbFormat);

        jFrameMain.getMsComponent().addNewMediaListener(this);

        cmbFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFilters();
            }
        });

        refreshModel();
    }

    private void populateFormatCmb() {
        var format = jFrameMain.getMyFiles();
        DefaultComboBoxModel<String> dcbm = new DefaultComboBoxModel<>();
        dcbm.addElement("All");
        dcbm.addElement("Video");
        dcbm.addElement("Audio");

        cmbFormat.setModel(dcbm);
    }

    private void applyFilters() {

        RowFilter<MyFileTableModel, Integer> rf = RowFilter.regexFilter("(?i)" + Pattern.quote(txtFilter.getText()), 1);

        String filterText = cmbFormat.getSelectedItem().toString();

        if (filterText != null && !filterText.isEmpty() && !filterText.equals("All")) {
            RowFilter<MyFileTableModel, Integer> asdfs = RowFilter.regexFilter(filterText.toLowerCase() + ".*", 3);
            ArrayList<RowFilter<MyFileTableModel, Integer>> andFilters = new ArrayList<>();
            andFilters.add(rf);
            andFilters.add(asdfs);
            rf = RowFilter.andFilter(andFilters);
        }

        sorter.setRowFilter(rf);
        //System.out.println("DEBUG - Expected result: " + mftm.getValueAt(0, 2));
        //System.out.println("DEBUG -  Filter: " + cmbFormat.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrDwnld = new javax.swing.JScrollPane();
        tblDownloads = new javax.swing.JTable();
        lblDownloads = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();
        btnDeleteItem = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        lblLocal = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        lblBoth = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblAction = new javax.swing.JLabel();

        setLayout(null);

        tblDownloads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrDwnld.setViewportView(tblDownloads);

        add(scrDwnld);
        scrDwnld.setBounds(30, 70, 700, 190);

        lblDownloads.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDownloads.setText("Files");
        add(lblDownloads);
        lblDownloads.setBounds(40, 30, 70, 20);

        lblFormat.setText("Choose format");
        add(lblFormat);
        lblFormat.setBounds(400, 30, 90, 16);

        btnDeleteItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteItem.setText("Delete selected item");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });
        add(btnDeleteItem);
        btnDeleteItem.setBounds(260, 290, 180, 23);

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });
        add(txtFilter);
        txtFilter.setBounds(200, 20, 190, 30);

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        add(btnUpload);
        btnUpload.setBounds(500, 290, 72, 23);

        btnDownload.setText("Download");
        btnDownload.setToolTipText("");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        add(btnDownload);
        btnDownload.setBounds(620, 290, 100, 23);

        lblLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/local.png"))); // NOI18N
        lblLocal.setText("Local");
        add(lblLocal);
        lblLocal.setBounds(20, 280, 50, 16);

        lblNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloud.png"))); // NOI18N
        lblNetwork.setText("Network");
        add(lblNetwork);
        lblNetwork.setBounds(90, 280, 70, 16);

        lblBoth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloud-storage.png"))); // NOI18N
        lblBoth.setText("Both");
        add(lblBoth);
        lblBoth.setBounds(170, 280, 60, 16);

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        lblSearch.setToolTipText("Search");
        add(lblSearch);
        lblSearch.setBounds(170, 20, 30, 30);

        lblAction.setText("Choose an action to perform...");
        add(lblAction);
        lblAction.setBounds(260, 270, 470, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        modelRow = tblDownloads.convertRowIndexToModel(tblDownloads.getSelectedRow());
        ArrayList<MyFile> files = jFrameMain.getMyFiles();
        MyFile currentFile = files.get(modelRow);
        if (!files.isEmpty()) {
            currentFile.delete();
            jFrameMain.deleteFile(modelRow);
            refreshModel();
            lblAction.setText("File has been successfully deleted.");
            lblAction.setForeground(new Color(0, 153, 51));

        }
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        int selectedRow = tblDownloads.convertRowIndexToModel(tblDownloads.getSelectedRow());
        MyFile currentFile = allFiles.get(selectedRow);
        try {
            if (currentFile.canBeUploaded()) {
                jFrameMain.getMsComponent().uploadFileMultipart(currentFile.getFile(), currentFile.getDownloadedFrom());
                lblAction.setText("File has been successfully uploaded.");
                lblAction.setForeground(new Color(0, 153, 51));
            } else if (currentFile.canBeDownloaded()) {
                JOptionPane.showMessageDialog(this, "File not found on your computer", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "File has already been uploaded.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        try {
            int selectedRow = tblDownloads.convertRowIndexToModel(tblDownloads.getSelectedRow());
            MyFile currentFile = allFiles.get(selectedRow);
            if (currentFile.canBeDownloaded()) {                
                File targetFile = new File(jFrameMain.getSaveToPath() + "\\" + currentFile.getMedia().mediaFileName);
                jFrameMain.getMsComponent().downloadMedia(currentFile.getMedia().id, targetFile);
                currentFile.setFile(targetFile);
                jFrameMain.addNewFile(currentFile);
                
                lblAction.setText("File has been successfully downloaded.");
                lblAction.setForeground(new Color(0, 153, 51));
            } else {
                JOptionPane.showMessageDialog(this, "File cannot be downloaded. You already have this.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        applyFilters();
    }//GEN-LAST:event_txtFilterKeyReleased

    void refreshModel() {
        populateFormatCmb();

        allFiles.clear();

        ArrayList<MyFile> localFiles = jFrameMain.getMyFiles();
        allFiles.addAll(localFiles);

        for (Media media : discoveredFiles) {
            MyFile matchingFile = null;

            for (MyFile localFile : jFrameMain.getMyFiles()) {
                if (media.mediaFileName.equals(localFile.getFileName())) {
                    matchingFile = localFile;
                }
            }

            if (matchingFile != null) {
                matchingFile.setMedia(media);
            } else {
                allFiles.add(new MyFile(media));
            }
        }

        MyFileTableModel newModel = new MyFileTableModel(allFiles);
        sorter = new TableRowSorter<>(newModel);
        tblDownloads.setRowSorter(sorter);
        tblDownloads.setModel(newModel);
    }

    @Override
    public void newMediaAdded(NewMediaEventObject object) {
        List<Media> newMedia = object.getMedia();

        for (Media media : newMedia) {
            boolean mediaExists = false;
            for (Media discoveredFile : discoveredFiles) {
                if (media.mediaFileName.equals(discoveredFile.mediaFileName)) {
                    mediaExists = true;
                    break;
                }
            }
            if (mediaExists) {
                continue;
            }
            discoveredFiles.add(media);
        }

        refreshModel();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel lblAction;
    private javax.swing.JLabel lblBoth;
    private javax.swing.JLabel lblDownloads;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JScrollPane scrDwnld;
    private javax.swing.JTable tblDownloads;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

}
