/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// <a href="https://www.flaticon.com/free-icons/popular" title="popular icons">Popular icons created by Indygo - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/ui" title="ui icons">Ui icons created by Freepik - Flaticon</a> 
// <a href="https://www.flaticon.com/free-icons/cute" title="cute icons">Cute icons created by Backwoods - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/folder" title="folder icons">Folder icons created by DinosoftLabs - Flaticon</a>
package com.carbonell.melodyseer;

import javax.swing.SwingWorker;
import java.io.*;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;

/**
 *
 * @author marta
 */
public class Preferences extends javax.swing.JFrame {
    
    private String YTDLP_PATH = "C:\\Users\\marta\\yt-dlp\\yt-dlp.exe"; // only works if it's hard-codded :( :(
    private String saveToPath;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Preferences.class.getName());

    /**
     * Creates new form Main
     */
    public Preferences() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpFormat = new javax.swing.ButtonGroup();
        pnlMainPanel = new javax.swing.JPanel();
        lblUrlRequest = new javax.swing.JLabel();
        txtUrlRequest = new javax.swing.JTextField();
        lblFormatRequest = new javax.swing.JLabel();
        radVideo = new javax.swing.JRadioButton();
        radMp3 = new javax.swing.JRadioButton();
        btnDownload = new javax.swing.JButton();
        lblProgress = new javax.swing.JLabel();
        prgDownloadProgress = new javax.swing.JProgressBar();
        scrOutput = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();
        btnChooser = new javax.swing.JButton();
        lblSaveTo = new javax.swing.JLabel();
        chkOpen = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Melody Seer");
        setMinimumSize(new java.awt.Dimension(800, 800));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        pnlMainPanel.setMaximumSize(new java.awt.Dimension(800, 800));
        pnlMainPanel.setMinimumSize(new java.awt.Dimension(800, 800));
        pnlMainPanel.setName("pnlMainPanel"); // NOI18N
        pnlMainPanel.setPreferredSize(new java.awt.Dimension(800, 800));
        pnlMainPanel.setVerifyInputWhenFocusTarget(false);
        pnlMainPanel.setLayout(null);

        lblUrlRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yt.png"))); // NOI18N
        lblUrlRequest.setText("Insert video URL here:");
        pnlMainPanel.add(lblUrlRequest);
        lblUrlRequest.setBounds(50, 40, 170, 30);

        txtUrlRequest.setToolTipText("write your URL here");
        pnlMainPanel.add(txtUrlRequest);
        txtUrlRequest.setBounds(220, 40, 510, 30);

        lblFormatRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/choose.png"))); // NOI18N
        lblFormatRequest.setText("Choose format:");
        pnlMainPanel.add(lblFormatRequest);
        lblFormatRequest.setBounds(50, 80, 170, 20);

        grpFormat.add(radVideo);
        radVideo.setSelected(true);
        radVideo.setText("Video");
        pnlMainPanel.add(radVideo);
        radVideo.setBounds(220, 80, 98, 20);

        grpFormat.add(radMp3);
        radMp3.setText("MP3");
        radMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMp3ActionPerformed(evt);
            }
        });
        pnlMainPanel.add(radMp3);
        radMp3.setBounds(300, 80, 47, 20);

        btnDownload.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/downloadyt.png"))); // NOI18N
        btnDownload.setText("DOWNLOAD");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnDownload);
        btnDownload.setBounds(280, 170, 230, 60);

        lblProgress.setText("Progress:");
        pnlMainPanel.add(lblProgress);
        lblProgress.setBounds(60, 270, 150, 20);
        pnlMainPanel.add(prgDownloadProgress);
        prgDownloadProgress.setBounds(230, 280, 510, 15);

        txaOutput.setColumns(20);
        txaOutput.setRows(5);
        scrOutput.setViewportView(txaOutput);

        pnlMainPanel.add(scrOutput);
        scrOutput.setBounds(50, 340, 690, 180);

        btnChooser.setText("Choose...");
        btnChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooserActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnChooser);
        btnChooser.setBounds(220, 110, 100, 23);

        lblSaveTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        lblSaveTo.setText("Save to...");
        pnlMainPanel.add(lblSaveTo);
        lblSaveTo.setBounds(50, 120, 100, 16);

        chkOpen.setSelected(true);
        chkOpen.setText("Open file after download");
        chkOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpenActionPerformed(evt);
            }
        });
        pnlMainPanel.add(chkOpen);
        chkOpen.setBounds(370, 110, 190, 20);

        getContentPane().add(pnlMainPanel);
        pnlMainPanel.setBounds(0, 0, 800, 800);
        pnlMainPanel.getAccessibleContext().setAccessibleName("Melody Seer");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radMp3ActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed

        if(radMp3.isSelected()) {
            downloadAudio();
        } else if(radVideo.isSelected()) {
            downloadVideo();
        } else {
            System.out.println("Error: Check radButton");
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooserActionPerformed
      
        // https://www.youtube.com/watch?v=HQ8JAbHmOvs
        // https://stackoverflow.com/questions/10083447/selecting-folder-destination-in-java
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        int option = chooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            saveToPath = f.getAbsolutePath();
            System.out.println(saveToPath);
        }
    }//GEN-LAST:event_btnChooserActionPerformed

    private void chkOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOpenActionPerformed

       private void downloadVideo() {
           // Código proporcionado por el profesor
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    // Replace "yourExecutable.exe" and arguments as needed
                    ProcessBuilder pb = new ProcessBuilder(YTDLP_PATH, txtUrlRequest.getText(), "-P", saveToPath);
                    pb.redirectErrorStream(true); // Combine stdout and stderr
                    Process process = pb.start();

                    // Read output
                    BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                    String line;
                    StringBuilder output = new StringBuilder();
                    while ((line = reader.readLine()) != null) {
                        output.append(line).append("\n");
                        publish(line); // https://stackoverflow.com/questions/18535303/how-are-the-publish-and-process-methods-on-swingworker-properly-used                        
                    }

                    int exitCode = process.waitFor();
                    
                    publish("Exited with code: " + exitCode + "\n");

                } catch (IOException | InterruptedException e) {
                    publish("Error: " + e.getMessage());
                }
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                System.out.println("Process> " + chunks.size() + " lines recieved. In thread " + Thread.currentThread());
                for (String line : chunks) {
                    Pattern pattern = Pattern.compile("\\d+\\.\\d+\\%");
                    Matcher matcher = pattern.matcher(line);
                    
                    System.out.println("\t" + line);
                    txaOutput.append(line + "\n");
                    
                    if(matcher.find()) {
                        // https://stackoverflow.com/questions/25277300/how-to-return-a-string-which-matches-the-regex-in-java
                        // https://docs.oracle.com/javase/tutorial/uiswing/components/progress.html
                        double progress = Double.parseDouble(matcher.group().replace("%",""));
                        prgDownloadProgress.setValue((int)progress);
                    }
                }

            }
        };
        worker.execute();
    }
    
       
    private void downloadAudio() {

        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    // Replace "yourExecutable.exe" and arguments as needed
                    ProcessBuilder pb = new ProcessBuilder(YTDLP_PATH,"-x", "--audio-format=mp3", "-P", saveToPath, txtUrlRequest.getText());
                    pb.redirectErrorStream(true); // Combine stdout and stderr
                    Process process = pb.start();

                    // Read output
                    BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                    String line;
                    StringBuilder output = new StringBuilder();
                    while ((line = reader.readLine()) != null) {
                        output.append(line).append("\n");
                        publish(line); // https://stackoverflow.com/questions/18535303/how-are-the-publish-and-process-methods-on-swingworker-properly-used                        
                    }

                    int exitCode = process.waitFor();
                    
                    publish("Exited with code: " + exitCode + "\n");

                } catch (IOException | InterruptedException e) {
                    publish("Error: " + e.getMessage());
                }
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                System.out.println("Process> " + chunks.size() + " lines recieved. In thread " + Thread.currentThread());
                for (String line : chunks) {
                    Pattern pattern = Pattern.compile("\\d+\\.\\d+\\%");
                    Matcher matcher = pattern.matcher(line);
                    
                    System.out.println("\t" + line);
                    txaOutput.append(line + "\n");
                    
                    if(matcher.find()) {
                        // https://stackoverflow.com/questions/25277300/how-to-return-a-string-which-matches-the-regex-in-java
                        // https://docs.oracle.com/javase/tutorial/uiswing/components/progress.html
                        double progress = Double.parseDouble(matcher.group().replace("%",""));
                        prgDownloadProgress.setValue((int)progress);
                    }
                }

            }
        };
        worker.execute();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Preferences().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooser;
    private javax.swing.JButton btnDownload;
    private javax.swing.JCheckBox chkOpen;
    private javax.swing.ButtonGroup grpFormat;
    private javax.swing.JLabel lblFormatRequest;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblSaveTo;
    private javax.swing.JLabel lblUrlRequest;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JProgressBar prgDownloadProgress;
    private javax.swing.JRadioButton radMp3;
    private javax.swing.JRadioButton radVideo;
    private javax.swing.JScrollPane scrOutput;
    private javax.swing.JTextArea txaOutput;
    private javax.swing.JTextField txtUrlRequest;
    // End of variables declaration//GEN-END:variables
}
