/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

import java.io.File;
import javax.swing.JFileChooser;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author marta
 */
public class PreferencesPanel extends javax.swing.JPanel {

    Main jFrameMain;

    /**
     * Creates new form PreferencesPanel Implements MigLayout for visualization
     *
     * @param jFrameMain an object from our <code>Main</code>, which deals with
     * variables used across the app
     */
    public PreferencesPanel(Main jFrameMain) {
        initComponents();
        setSize(725, 200);
        this.jFrameMain = jFrameMain;
        txtYtDlpPath.setText(jFrameMain.getYtdlp_path());
        txtTemporaryFiles.setText(jFrameMain.getSaveToPathTemp());

        MigLayout layout = new MigLayout(
                "wrap 3, fillx, align center top",
                "[right][left][left]",
                "[]12[]12[]12[]12[]12[]12[]"
        );
        setLayout(layout);

        add(lblGoBack, "left, wrap");

        add(lblChoosePath);
        add(txtYtDlpPath, "growx");
        add(btnChoosePath);

        add(lblTempFiles);
        add(txtTemporaryFiles, "growx");
        add(btnTempFiles);

        add(lblLimitDwld);
        add(cmbLimitDwld);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGoBack = new javax.swing.JLabel();
        lblChoosePath = new javax.swing.JLabel();
        txtYtDlpPath = new javax.swing.JTextField();
        btnChoosePath = new javax.swing.JButton();
        lblTempFiles = new javax.swing.JLabel();
        txtTemporaryFiles = new javax.swing.JTextField();
        btnTempFiles = new javax.swing.JButton();
        lblLimitDwld = new javax.swing.JLabel();
        cmbLimitDwld = new javax.swing.JComboBox<>();

        setLayout(null);

        lblGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        lblGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoBackMouseClicked(evt);
            }
        });
        add(lblGoBack);
        lblGoBack.setBounds(20, 10, 40, 40);

        lblChoosePath.setText("Select yt-dlp path");
        add(lblChoosePath);
        lblChoosePath.setBounds(60, 50, 100, 16);
        add(txtYtDlpPath);
        txtYtDlpPath.setBounds(230, 40, 410, 30);

        btnChoosePath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        btnChoosePath.setText("Choose");
        btnChoosePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePathActionPerformed(evt);
            }
        });
        add(btnChoosePath);
        btnChoosePath.setBounds(660, 40, 110, 23);

        lblTempFiles.setText("Path to store temporary files...");
        add(lblTempFiles);
        lblTempFiles.setBounds(60, 110, 180, 16);
        add(txtTemporaryFiles);
        txtTemporaryFiles.setBounds(230, 100, 410, 30);

        btnTempFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        btnTempFiles.setText("Choose");
        btnTempFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempFilesActionPerformed(evt);
            }
        });
        add(btnTempFiles);
        btnTempFiles.setBounds(660, 110, 110, 23);

        lblLimitDwld.setText("Limit download to...");
        add(lblLimitDwld);
        lblLimitDwld.setBounds(60, 150, 150, 16);

        cmbLimitDwld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't limit", "1 MB/s", "5 MB/s", "10 MB/s" }));
        cmbLimitDwld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLimitDwldActionPerformed(evt);
            }
        });
        add(cmbLimitDwld);
        cmbLimitDwld.setBounds(240, 150, 120, 22);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens a <code>JFileChooser</code> for directories and sets it as a path
     * to store temporary files Sets the corresponding textfield to the selected
     * path
     *
     * @param evt clicking on the "Choose" button to select a folder for temporary files
     */
    private void btnTempFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempFilesActionPerformed
        // https://stackoverflow.com/questions/10083447/selecting-folder-destination-in-java
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            jFrameMain.setSaveToPathTemp(f.getAbsolutePath().toString());
            txtTemporaryFiles.setText(jFrameMain.getSaveToPathTemp());
        }

    }//GEN-LAST:event_btnTempFilesActionPerformed

    /**
     * Selects the maximum download speed
     *
     * @param evt click on combo box option
     */
    private void cmbLimitDwldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLimitDwldActionPerformed
        jFrameMain.setSelectedSpeed(cmbLimitDwld.getSelectedItem().toString());
    }//GEN-LAST:event_cmbLimitDwldActionPerformed

    /**
     * Opens a <code>JFileChooser</code> for directories and sets it as a path to store the downloaded files 
     * Sets the corresponding textfield to the selected path
     *
     * @param evt clicking on the "Choose" button to select a folder for downloaded files
     */
    private void btnChoosePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePathActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            jFrameMain.setYtdlp_path(f.getAbsolutePath().toString());
            txtYtDlpPath.setText(jFrameMain.getYtdlp_path());
        }
    }//GEN-LAST:event_btnChoosePathActionPerformed

    /**
     * Goes back to the Download Panel
     * 
     * @param evt click on the arrow icon
     */
    private void lblGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoBackMouseClicked
        jFrameMain.showDownloadPanel();
    }//GEN-LAST:event_lblGoBackMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoosePath;
    private javax.swing.JButton btnTempFiles;
    private javax.swing.JComboBox<String> cmbLimitDwld;
    private javax.swing.JLabel lblChoosePath;
    private javax.swing.JLabel lblGoBack;
    private javax.swing.JLabel lblLimitDwld;
    private javax.swing.JLabel lblTempFiles;
    private javax.swing.JTextField txtTemporaryFiles;
    private javax.swing.JTextField txtYtDlpPath;
    // End of variables declaration//GEN-END:variables
}
