/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author marta
 */
public class PreferencesPanel extends javax.swing.JPanel {

    Main jFrameMain;

    /**
     * Creates new form PreferencesPanel
     *
     * @param jFrameMain
     */
    public PreferencesPanel(Main jFrameMain) {
        initComponents();
        setSize(725, 200);
        this.jFrameMain = jFrameMain;
        txtYtDlpPath.setText(jFrameMain.getYtdlp_path());
        txtTemporaryFiles.setText(jFrameMain.getSaveToPathTemp());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTempFiles = new javax.swing.JLabel();
        btnTempFiles = new javax.swing.JButton();
        lblLimitDwld = new javax.swing.JLabel();
        cmbLimitDwld = new javax.swing.JComboBox<>();
        lblChoosePath = new javax.swing.JLabel();
        btnChoosePath = new javax.swing.JButton();
        lblGoBack = new javax.swing.JLabel();
        txtYtDlpPath = new javax.swing.JTextField();
        txtTemporaryFiles = new javax.swing.JTextField();

        setLayout(null);

        lblTempFiles.setText("Path to store temporary files...");
        add(lblTempFiles);
        lblTempFiles.setBounds(60, 110, 180, 16);

        btnTempFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        btnTempFiles.setText("Choose");
        btnTempFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempFilesActionPerformed(evt);
            }
        });
        add(btnTempFiles);
        btnTempFiles.setBounds(660, 110, 110, 23);

        lblLimitDwld.setText("Limit download to...");
        add(lblLimitDwld);
        lblLimitDwld.setBounds(60, 150, 150, 16);

        cmbLimitDwld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't limit", "1 MB/s", "5 MB/s", "10 MB/s" }));
        cmbLimitDwld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLimitDwldActionPerformed(evt);
            }
        });
        add(cmbLimitDwld);
        cmbLimitDwld.setBounds(240, 150, 120, 22);

        lblChoosePath.setText("Select yt-dlp path");
        add(lblChoosePath);
        lblChoosePath.setBounds(60, 50, 100, 16);

        btnChoosePath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        btnChoosePath.setText("Choose");
        btnChoosePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePathActionPerformed(evt);
            }
        });
        add(btnChoosePath);
        btnChoosePath.setBounds(660, 40, 110, 23);

        lblGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        lblGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoBackMouseClicked(evt);
            }
        });
        add(lblGoBack);
        lblGoBack.setBounds(20, 10, 40, 40);

        txtYtDlpPath.setPreferredSize(new java.awt.Dimension(64, 22));
        add(txtYtDlpPath);
        txtYtDlpPath.setBounds(230, 40, 410, 30);
        add(txtTemporaryFiles);
        txtTemporaryFiles.setBounds(230, 100, 410, 30);
    }// </editor-fold>//GEN-END:initComponents


    private void btnTempFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempFilesActionPerformed
                // https://stackoverflow.com/questions/10083447/selecting-folder-destination-in-java
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            jFrameMain.setSaveToPathTemp(f.getAbsolutePath().toString());
            txtTemporaryFiles.setText(jFrameMain.getSaveToPathTemp());
        }
      
    }//GEN-LAST:event_btnTempFilesActionPerformed

    private void cmbLimitDwldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLimitDwldActionPerformed
        jFrameMain.setSelectedSpeed(cmbLimitDwld.getSelectedItem().toString());
    }//GEN-LAST:event_cmbLimitDwldActionPerformed

    private void btnChoosePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePathActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            jFrameMain.setYtdlp_path(f.getAbsolutePath().toString());
            txtYtDlpPath.setText(jFrameMain.getYtdlp_path());
        }
    }//GEN-LAST:event_btnChoosePathActionPerformed

    private void lblGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoBackMouseClicked
       jFrameMain.showDownloadPanel();
    }//GEN-LAST:event_lblGoBackMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoosePath;
    private javax.swing.JButton btnTempFiles;
    private javax.swing.JComboBox<String> cmbLimitDwld;
    private javax.swing.JLabel lblChoosePath;
    private javax.swing.JLabel lblGoBack;
    private javax.swing.JLabel lblLimitDwld;
    private javax.swing.JLabel lblTempFiles;
    private javax.swing.JTextField txtTemporaryFiles;
    private javax.swing.JTextField txtYtDlpPath;
    // End of variables declaration//GEN-END:variables
}
