/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// <a href="https://www.flaticon.com/free-icons/popular" title="popular icons">Popular icons created by Indygo - Flaticon</a>
// <a href="https://www.flaticon.com/free-icons/ui" title="ui icons">Ui icons created by Freepik - Flaticon</a> 
// <a href="https://www.flaticon.com/free-icons/cute" title="cute icons">Cute icons created by Backwoods - Flaticon</a>
package com.carbonell.melodyseer;

/**
 *
 * @author marta
 */
public class Preferences extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Preferences.class.getName());

    /**
     * Creates new form Main
     */
    public Preferences() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainPanel = new javax.swing.JPanel();
        lblUrlRequest = new javax.swing.JLabel();
        txtUrlRequest = new javax.swing.JTextField();
        lblFormatRequest = new javax.swing.JLabel();
        btnMp3 = new javax.swing.JRadioButton();
        bntVideo = new javax.swing.JRadioButton();
        btnDownload = new javax.swing.JButton();
        lblProgress = new javax.swing.JLabel();
        prgDownloadProgress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Melody Seer");
        setMinimumSize(new java.awt.Dimension(800, 800));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        pnlMainPanel.setMaximumSize(new java.awt.Dimension(800, 800));
        pnlMainPanel.setMinimumSize(new java.awt.Dimension(800, 800));
        pnlMainPanel.setName("pnlMainPanel"); // NOI18N
        pnlMainPanel.setPreferredSize(new java.awt.Dimension(800, 800));
        pnlMainPanel.setVerifyInputWhenFocusTarget(false);
        pnlMainPanel.setLayout(null);

        lblUrlRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yt.png"))); // NOI18N
        lblUrlRequest.setText("Insert video URL here:");
        pnlMainPanel.add(lblUrlRequest);
        lblUrlRequest.setBounds(70, 40, 140, 30);

        txtUrlRequest.setToolTipText("write your URL here");
        pnlMainPanel.add(txtUrlRequest);
        txtUrlRequest.setBounds(220, 40, 510, 20);

        lblFormatRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/choose.png"))); // NOI18N
        lblFormatRequest.setText("Choose format:");
        pnlMainPanel.add(lblFormatRequest);
        lblFormatRequest.setBounds(100, 80, 110, 20);

        btnMp3.setText("MP3");
        btnMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMp3ActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnMp3);
        btnMp3.setBounds(220, 80, 47, 20);

        bntVideo.setText("Video");
        pnlMainPanel.add(bntVideo);
        bntVideo.setBounds(290, 80, 98, 20);

        btnDownload.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/downloadyt.png"))); // NOI18N
        btnDownload.setText("DOWNLOAD");
        pnlMainPanel.add(btnDownload);
        btnDownload.setBounds(270, 130, 230, 60);

        lblProgress.setText("Progress:");
        pnlMainPanel.add(lblProgress);
        lblProgress.setBounds(150, 230, 50, 20);
        pnlMainPanel.add(prgDownloadProgress);
        prgDownloadProgress.setBounds(220, 235, 510, 10);

        getContentPane().add(pnlMainPanel);
        pnlMainPanel.setBounds(0, 0, 800, 800);
        pnlMainPanel.getAccessibleContext().setAccessibleName("Melody Seer");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMp3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Preferences().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bntVideo;
    private javax.swing.JButton btnDownload;
    private javax.swing.JRadioButton btnMp3;
    private javax.swing.JLabel lblFormatRequest;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblUrlRequest;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JProgressBar prgDownloadProgress;
    private javax.swing.JTextField txtUrlRequest;
    // End of variables declaration//GEN-END:variables
}
