/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carbonell.melodyseer;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author marta
 */
public class PreferencesPanel extends javax.swing.JPanel {

    Main jFrameMain;

    /**
     * Creates new form PreferencesPanel
     *
     * @param jFrameMain
     */
    public PreferencesPanel(Main jFrameMain) {
        initComponents();
        setSize(725, 200);
        this.jFrameMain = jFrameMain;

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTempFiles = new javax.swing.JLabel();
        btnTempFiles = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        lblLimitDwld = new javax.swing.JLabel();
        cmbLimitDwld = new javax.swing.JComboBox<>();

        setLayout(null);

        lblTempFiles.setText("Path to store temporary files...");
        add(lblTempFiles);
        lblTempFiles.setBounds(50, 50, 180, 16);

        btnTempFiles.setText("Choose");
        btnTempFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempFilesActionPerformed(evt);
            }
        });
        add(btnTempFiles);
        btnTempFiles.setBounds(250, 40, 75, 23);

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnHide.setText("Hide preferences");
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });
        add(btnHide);
        btnHide.setBounds(490, 40, 160, 40);

        lblLimitDwld.setText("Limit download to...");
        add(lblLimitDwld);
        lblLimitDwld.setBounds(50, 90, 150, 16);

        cmbLimitDwld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't limit", "10 MB/s", "15 MB/s", "20 MB/s", "25 MB/s" }));
        cmbLimitDwld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLimitDwldActionPerformed(evt);
            }
        });
        add(cmbLimitDwld);
        cmbLimitDwld.setBounds(230, 90, 120, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        jFrameMain.showDownloadPanel();
    }//GEN-LAST:event_btnHideActionPerformed

    private void btnTempFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempFilesActionPerformed
                // https://stackoverflow.com/questions/10083447/selecting-folder-destination-in-java
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            jFrameMain.setSaveToPathTemp(f.getAbsolutePath().toString());
        }
      
    }//GEN-LAST:event_btnTempFilesActionPerformed

    private void cmbLimitDwldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLimitDwldActionPerformed
        jFrameMain.setSelectedSpeed(cmbLimitDwld.getSelectedItem().toString());
    }//GEN-LAST:event_cmbLimitDwldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnTempFiles;
    private javax.swing.JComboBox<String> cmbLimitDwld;
    private javax.swing.JLabel lblLimitDwld;
    private javax.swing.JLabel lblTempFiles;
    // End of variables declaration//GEN-END:variables
}
